config/routes.rb
Rails.application.routes.draw do
  get 'geoservice/index'
  resources :geolocations
  scope '/api' do
    get '/show/:id', to: "geo_api#show", as: "show", defaults: {format: :json}
    get '/list', to: "geo_api#index", as: "list", defaults: {format: :json}
    post '/create', to: "geo_api#create", as: "create", defaults: {format: :json}
    delete '/delete/:id',to: "geo_api#destroy", as: "delete", defaults: {format: :json}
    put '/update/:id',to: "geo_api#update", as: "update", defaults: {format: :json}
    get '/closest/:lat/:lng', to: "geo_api#closest", as: "closest", defaults: {format: :json}
    get '/in_radius/:lat/:lng', to: "geo_api#in_radius", as: "find_in_radius", defaults: {format: :json}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/geolocation.rb
class Geolocation < ApplicationRecord
  validates :message, presence: true
  validates :lat, presence:true, numericality: {only_float: true}
  validates :lng, presence:true, numericality: {only_float: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/geo_api_controller.rb
class GeoApiController < ApplicationController
  include GeoserviceHelper
  skip_before_action :verify_authenticity_token
  before_filter :find_geolocation, :except => [:index, :create, :closest, :in_radius]
  def find_geolocation
    @geolocation = Geolocation.find(params[:id])
  end

  def index
    @geolocations = Geolocation.all
    respond_to do |format|
      format.json { render json: {data: @geolocations} , status: :ok }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @geolocation, status: :ok }
    end
  end

  def create
    @geolocation = Geolocation.new(geolocation_get_params)
    respond_to do |format|
      if @geolocation.save
        format.json { render json: @geolocation, status: :created }
      else
        format.json { render json: @geolocation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @geolocation.update_attributes(geolocation_get_params)
        format.json { render json: @geolocation, status: :ok }
      else
        format.json { render json: @geolocation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @geolocation.destroy
        format.json { head :no_content, status: :ok }
      else
        format.json { render json: @geolocation.errors, status: :unprocessable_entity }
      end
    end
  end

  def closest
    closest = find_closest(params[:lat],params[:lng])
    respond_to do |format|
      format.json { render json: closest }
    end
  end

  def in_radius
    markers_in_radius = find_in_radius(params[:lat],params[:lng])
    respond_to do |format|
      format.json { render json: {markers: markers_in_radius} }
    end
  end

  private
    def geolocation_get_params
      params.permit(:message, :lat, :lng)
    end
end

app/controllers/geolocations_controller.rb
class GeolocationsController < ApplicationController
  before_filter :find_geolocation, :except => [:index, :create, :new]

  def find_geolocation
    @geolocation = Geolocation.find(params[:id])
  end

  def index
    @geolocations = Geolocation.all
  end

  def show
    render 'show'
  end

  def new
    @geolocation = Geolocation.new
  end

  def edit
    @geolocation = Geolocation.find(params[:id])
  end

  def create
    @geolocation = Geolocation.new(geolocation_get_params)

    if @geolocation.save
      redirect_to @geolocation
    else
      render 'new'
    end
  end

  def update

    if @geolocation.update(geolocation_get_params)
      redirect_to @geolocation
    else
      render 'edit'
    end
  end

  def destroy
    @geolocation.destroy
    redirect_to geolocations_path
  end

  private
    def geolocation_get_params
      params.require(:geolocation).permit(:message, :lat, :lng)
    end
end

app/controllers/geoservice_controller.rb
class GeoserviceController < ApplicationController
  def index
    @geos = Geolocation.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geo_api_helper.rb
module GeoApiHelper
end

app/helpers/geolocations_helper.rb
module GeolocationsHelper
end

app/helpers/geoservice_helper.rb
require 'geocoder'
module GeoserviceHelper
  def find_in_radius(lat,lng)
    radius_km = 100
    result_markers = []
    geolocations = Geolocation.all
    geolocations.each do |geol|
      distance_from_location = calculate_distance_in_km([geol.lat, geol.lng], [lat, lng])
      if distance_from_location <= radius_km
        result_markers.push(geol)
      end
    end
    return result_markers
  end

  def find_closest(lat,lng)
    r = 6371
    distances = []
    closest = -1
    geolocations = Geolocation.all
    i = 0
    geolocations.each do |geol|
      distances[i] = calculate_distance_in_km([geol.lat, geol.lng], [lat, lng])
      if  closest == -1 or distances[i] < distances[closest]
        closest = i;
      end
      i = i+1
    end
    if closest != -1 and geolocations[closest]
      return geolocations[closest]
    else
      return nil
    end

  end
  private
    def rad(x)
      x * Math::PI / 180
    end
    def calculate_distance_in_km (aLocation,bLocation)
      return Geocoder::Calculations.distance_between(aLocation, bLocation) * 1.60934
    end
end

app/views/geolocations/edit.html.erb
<%= form_for Geolocation.new, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>

<% if @geolocation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@geolocation.errors.count, "error") %> prohibited
        this geolocation from being saved:
      </h2>
      <ul>
        <% @geolocation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.text_field :message %>
  <%= f.text_field :lat %>
  <%= f.text_field :lng %>

  <%= f.submit "Create" %>
<% end %>

app/views/geolocations/index.html.erb
<h1>Listing geolocations</h1>
<%= link_to 'New geolocation', new_geolocation_path %>
<table>
  <tr>
    <th>Message</th>
    <th>Lattitude</th>
    <th>Longtitude</th>
  </tr>

  <% @geolocations.each do |geolocation| %>
    <tr>
      <td><%= geolocation.message %></td>
      <td><%= geolocation.lat %></td>
      <td><%= geolocation.lng %></td>
      <td><%= link_to 'Show', geolocation_path(geolocation) %></td>
      <td><%= link_to 'Edit', edit_geolocation_path(geolocation) %></td>
      <td><%= link_to 'Destroy', geolocation_path(geolocation),
             method: :delete,
             data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/geolocations/new.html.erb
<%= form_for Geolocation.new, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>

<% if @geolocation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@geolocation.errors.count, "error") %> prohibited
        this geolocation from being saved:
      </h2>
      <ul>
        <% @geolocation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.text_field :message %>
  <%= f.text_field :lat %>
  <%= f.text_field :lng %>

  <%= f.submit "Create" %>
<% end %>

app/views/geolocations/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @geolocation.message %>
</p>

<p>
  <strong>Lattitude:</strong>
  <%= @geolocation.lat %>
</p>

<p>
  <strong>Longtitude:</strong>
  <%= @geolocation.lng %>
</p>

app/views/geoservice/index.html.erb
<h1>Geocache service</h1>
<div>Click left mouse button to add new marker to the map.</div>
<div>Click right mouse button to add new start point for searching. Then you can search for closest marker or find all markers in radius of 100 km. Wanted markers will turn up blue color.</div>
<div>Search point latitude:<span id="search_lat"></span>, longitude:<span id="search_lng"></span></div>
<button id="closest_marker">Get closest marker</button>
<button id="find_markers_in_radius">Find all markers in radius</button>
<div id="map" style="height:500px;width:700px;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geocache</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBUbyKwHz3YtGHe0GbKBpcLEwIp8ETEtc4&libraries=geometry" ></script>
  </body>
</html>